<script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-maskmoney/3.0.2/jquery.maskMoney.min.js"></script>

<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.bundle.min.js" integrity="sha384-b5kHyXgcpbZJO/tY9Ul7kGkf1S0CWuKcCD38l8YkeH8z8QjE0GmW1gYU5S9FOnJ0" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.6.0/dist/umd/popper.min.js" integrity="sha384-KsvD1yqQ1/1+IA7gi3P0tyJcT3vR+NdBTt13hSJ2lnve8agRGXTTyNaBYmCR/Nwi" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.min.js" integrity="sha384-nsg8ua9HAw1y0W1btsyWgBklPnCUAFLuTMS2G72MMONqmOymq585AcH49TLBQObG" crossorigin="anonymous"></script>

<main class="container">
	<div class="bg-light p-5 rounded mt-3">
		<nav aria-label="breadcrumb">
			<ol class="breadcrumb">
				<li class="breadcrumb-item">
					<a class="btn btn-link btn-sm" href="<?=BASE_URL?>/venda/listar" role="button">Lista</a>
				</li>
				<li class="breadcrumb-item active btn btn-link btn-sm" aria-current="page">
					Cadastrar Venda
				</li>
			</ol>
		</nav>

		<h1>Cadastrar Venda</h1>

		<div class="row">
			<div class="col-md-6">
				<label for="valor" class="form-label">Valor</label>
				<input type="text" class="form-control" placeholder="Valor da Venda" id="valor">
			</div>
			<div class="col-md-4">
				<label for="valor" class="form-label">Vendedor</label>
				<select class="form-select" id="id_vendedor" aria-label="Vendedores">
					<?php foreach ($vendedores as $vendedor) : ?>
						<option value="<?= $vendedor['id'] ?? '' ?>">
							<?= $vendedor['nome'] ?? '' ?>
						</option>
					<?php endforeach; ?>
				</select>
			</div>
			<div class="col-md-2">
				<label for="valor" class="form-label">Comissão %</label>
				<input type="text" class="form-control" placeholder="Comissão" id="comissao" value="8.5" readonly>
			</div>
		</div>
		<button type="button" class="btn btn-success mt-3" id="btn_enviar">Enviar</button>
	</div>
</main>

<script>
	$(function() {
		$('#valor').maskMoney({
			thousands: '',
			decimal: '.',
		});

		$(document).on('click', '#btn_enviar', function() {
			var valor = $('#valor').val();
			var id_vendedor = $('#id_vendedor').val();
			var comissao = $('#comissao').val();

			$.ajax({
				url: '<?=BASE_URL?>/venda/cadastrar',
				type: 'post',
				data: {
					valor,
					id_vendedor,
					comissao
				}
			}).done(res => {
				var json = JSON.parse(res);
				// alert(json.mensagem);
				window.location.href = "<?=BASE_URL?>/venda/listar";
			});
		});
	});
</script>